"""initial_schema

Revision ID: 8698d824cd71
Revises: 
Create Date: 2026-06-20 12:11:53.465646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8698d824cd71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('scheme_name', sa.String(length=255), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('released_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('spent_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('doctor_count', sa.Integer(), nullable=True),
    sa.Column('nurse_count', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_no', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('taluk', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('patta_no', sa.String(length=50), nullable=True),
    sa.Column('area_acres', sa.Float(), nullable=True),
    sa.Column('land_type', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('teacher_count', sa.Integer(), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('schools')
    op.drop_table('scheme_enrollments')
    op.drop_table('land_records')
    op.drop_table('hospitals')
    op.drop_table('employees')
    op.drop_table('budget_allocations')
    # ### end Alembic commands ###
